import { useState } from "react";
import { jsPDF } from "jspdf";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { WiringDiagram } from "@/components/WiringDiagram";
import { InfoTooltip } from "@/components/ui/InfoTooltip";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/context/AuthContext";
import { AlertTriangle, CheckCircle, ChevronDown, ChevronUp, CircuitBoard, DollarSign, Download, ExternalLink, FileSpreadsheet, FileText, Lock, Zap } from "lucide-react";
import type { Configuration } from "./types";
import { formatUnit } from "./utils";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { saveAs } from "file-saver";

interface SolutionDetailModalProps {
  solution: Configuration;
  isOpen: boolean;
  onClose: () => void;
  showComponents: boolean;
  dataSource: "default" | "custom";
}

export const SolutionDetailModal = ({ solution, isOpen, onClose, showComponents, dataSource }: SolutionDetailModalProps) => {
  if (!solution) return null;

  const { isAuthenticated } = useAuth();
  const { toast } = useToast();
  const [showDiagram, setShowDiagram] = useState(false);

  const [laborCost, setLaborCost] = useState(0);
  const [shippingCost, setShippingCost] = useState(0);
  const [margin, setMargin] = useState(20);
  const [includeCostsInBom, setIncludeCostsInBom] = useState(true);

  const basePrice = solution.total_price;
  const costPrice = basePrice + laborCost + shippingCost;
  const finalPrice = costPrice * (1 + margin / 100);

  const AffiliateLink = ({ link }: { link?: string }) => {
    if (!link) return null;
    return (
      <a href={link} target="_blank" rel="noopener noreferrer" className="text-accent hover:underline flex items-center gap-1 mt-1">
        Buy from Affiliate <ExternalLink className="inline w-3 h-3" />
      </a>
    );
  };

  const downloadDatasheet_word = async () => {
    const watermark = new Paragraph({
      children: [
        new TextRun({
          text: "WATT BUILDER",
          color: "D9D9D9",
          size: 120,
          bold: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 3000 },
    });

    const doc = new Document({
      sections: [
        {
          properties: {},
          children: [
            new Paragraph({ text: "" }),
            new Paragraph({
              text: "BATTERY TECHNICAL DATASHEET",
              heading: HeadingLevel.TITLE,
              alignment: AlignmentType.CENTER,
            }),
            new Paragraph({
              children: [
                new TextRun({
                  text: "Generated by Watt Builder",
                  italics: true,
                  color: "666666",
                }),
              ],
              alignment: AlignmentType.CENTER,
              spacing: { after: 400 },
            }),

            new Paragraph({
              children: [
                new TextRun({ text: "Configuration: ", bold: true }),
                new TextRun(`${solution.series_cells}S ${solution.parallel_cells}P`),
              ],
            }),
            new Paragraph({
              children: [
                new TextRun({ text: "Cell Model: ", bold: true }),
                new TextRun(`${solution.cell.Brand} ${solution.cell.CellModelNo}`),
              ],
            }),

            new Paragraph({
              text: "Electrical Specifications",
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 400 },
            }),
            new Paragraph(`Nominal Voltage: ${solution.battery_voltage.toFixed(1)} V`),
            new Paragraph(`Capacity: ${solution.battery_capacity.toFixed(1)} Ah`),
            new Paragraph(`Total Energy: ${formatUnit(solution.battery_energy, "Wh")}`),
            new Paragraph(`Continuous Power: ${formatUnit(solution.continuous_power, "W")}`),
            new Paragraph(`Peak Power (30s): ${formatUnit(solution.peak_power, "W")}`),

            new Paragraph({
              text: "Mechanical Specifications",
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 400 },
            }),
            new Paragraph(`Cell Weight (total): ${solution.battery_weight.toFixed(2)} kg`),
            new Paragraph(
              `Cell Dimensions: ${solution.cell.Cell_Width} × ${solution.cell.Cell_Height} mm`
            ),

            new Paragraph({
              text: "Safety Assessment",
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 400 },
            }),
            new Paragraph(`Safety Score: ${solution.safety.safety_score}/100`),
            new Paragraph(
              `Status: ${solution.safety.is_safe ? "PASS" : "WARNING"}`
            ),
            new Paragraph(
              `Warnings: ${solution.safety.warnings.length
                ? solution.safety.warnings.join("; ")
                : "None"
              }`
            ),

            new Paragraph({
              spacing: { before: 600 },
              children: [
                new TextRun({
                  text:
                    "Disclaimer: This document is automatically generated and intended for preliminary engineering evaluation only.",
                  italics: true,
                  color: "666666",
                }),
              ],
            }),
          ],
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `Datasheet_${solution.series_cells}S${solution.parallel_cells}P.docx`);
  };


  const requireAuthForDownload = (action: () => void) => {
    if (!isAuthenticated) {
      toast({
        title: "Login required",
        description: "Log in to download documents.",
        variant: "destructive",
      });
      return;
    }

    action();
  };

  const downloadBOM = () => {
    const rows = [["Component", "Model", "Quantity", "Details"]];

    if (includeCostsInBom) {
      rows[0].push("Unit Price", "Total Price");
    }

    const addRow = (name: string, model: string, qty: number, details: string, unitPrice: number) => {
      const row = [name, model, qty.toString(), details];
      if (includeCostsInBom) {
        row.push(unitPrice.toFixed(2), (unitPrice * qty).toFixed(2));
      }
      rows.push(row);
    };

    const totalCells = solution.series_cells * solution.parallel_cells;
    addRow(
      "Battery Cells",
      solution.cell.CellModelNo,
      totalCells,
      `${solution.cell.NominalVoltage}V ${solution.cell.Capacity}mAh`,
      solution.cell.Price
    );

    if (solution.bms) addRow("BMS", solution.bms.model, 1, `Max ${solution.bms.a_max}A`, solution.bms.master_price || solution.bms.price);
    if (solution.fuse) addRow("Fuse", solution.fuse.model, 1, `${solution.fuse.a_max}A`, solution.fuse.price);
    if (solution.relay) addRow("Relay", solution.relay.model, 1, `${solution.relay.a_max}A`, solution.relay.price);
    if (solution.shunt) addRow("Shunt", solution.shunt.model, 1, `${solution.shunt.a_max}A`, solution.shunt.price);
    if (solution.cable) addRow("Cable (2m)", solution.cable.model, 1, `${solution.cable.section}mm²`, solution.cable.price);

    if (includeCostsInBom && laborCost > 0) rows.push(["Labor", "-", "1", "-", laborCost.toFixed(2), laborCost.toFixed(2)]);
    if (includeCostsInBom && shippingCost > 0) rows.push(["Shipping", "-", "1", "-", shippingCost.toFixed(2), shippingCost.toFixed(2)]);

    const csvContent = "data:text/csv;charset=utf-8," + rows.map((e) => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `BOM_${solution.series_cells}S${solution.parallel_cells}P_${solution.cell.CellModelNo}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  const downloadDatasheet_pdf = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let y = 30;

    // 🔹 Watermark
    doc.saveGraphicsState();

    // Opacidade
    doc.setGState(new (doc as any).GState({ opacity: 0.12 }));

    doc.setFont("Helvetica", "bold");
    doc.setFontSize(80);
    doc.setTextColor(150, 150, 150);

    // Centro real da página
    const centerX = pageWidth / 2 + 30;
    const centerY = pageHeight / 2 + 30;

    // Rotação em torno do centro
    doc.text("Watt Builder", centerX, centerY, {
      align: "center",
      angle: 45,
    });

    doc.restoreGraphicsState();

    // Reset styles
    doc.setTextColor(40, 40, 40);

    // Header
    doc.setFontSize(20);
    doc.text("Battery Technical Datasheet", margin, 20);

    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(`Generated by Watt Builder • ${new Date().toLocaleDateString()}`, margin, 26);

    const section = (title: string) => {
      y += 10;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(249, 115, 22);
      doc.text(title.toUpperCase(), margin, y);
      doc.line(margin, y + 2, pageWidth - margin, y + 2);
      y += 8;
      doc.setTextColor(0, 0, 0);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
    };

    const row = (label: string, value: string) => {
      doc.text(label, margin, y);
      doc.text(value, margin + 70, y);
      y += 6;
    };

    section("Project Overview");
    row("Configuration:", `${solution.series_cells}S ${solution.parallel_cells}P`);
    row("Cell Model:", `${solution.cell.Brand} ${solution.cell.CellModelNo}`);
    row("Total Cells:", `${solution.series_cells * solution.parallel_cells}`);

    section("Electrical Specifications");
    row("Nominal Voltage:", `${solution.battery_voltage.toFixed(1)} V`);
    row("Capacity:", `${solution.battery_capacity.toFixed(1)} Ah`);
    row("Total Energy:", formatUnit(solution.battery_energy, "Wh"));
    row("Continuous Power:", formatUnit(solution.continuous_power, "W"));
    row("Peak Power (30s):", formatUnit(solution.peak_power, "W"));

    section("Mechanical Specifications");
    row("Cell Weight:", `${solution.battery_weight.toFixed(2)} kg`);
    row(
      "Cell Dimensions:",
      `${solution.cell.Cell_Width} × ${solution.cell.Cell_Height} mm`
    );

    section("Safety");
    doc.setFont("helvetica", "bold");
    doc.text(
      `Safety Score: ${solution.safety.safety_score}/100`,
      margin,
      y
    );
    y += 6;

    doc.setFont("helvetica", "normal");
    if (solution.safety.warnings.length) {
      solution.safety.warnings.forEach((w) => {
        const t = doc.splitTextToSize(`• ${w}`, pageWidth - margin * 2);
        doc.text(t, margin, y);
        y += t.length * 5;
      });
    } else {
      doc.text("No critical warnings detected.", margin, y);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(130, 130, 130);
    doc.text(
      "This document is auto-generated by Watt Builder and intended for preliminary engineering analysis only.",
      margin,
      pageHeight - 15
    );

    doc.save(
      `Datasheet_${solution.series_cells}S${solution.parallel_cells}P_${solution.cell.CellModelNo}.pdf`
    );
  };

  const downloadDatasheet_txt = () => {
    const content = `
  TECHNICAL DATASHEET
  Generated by Watt Builder
  --------------------------------------------------
  Project Configuration: ${solution.series_cells}S${solution.parallel_cells}P
  Cell Model: ${solution.cell.Brand} ${solution.cell.CellModelNo}

  ELECTRICAL SPECIFICATIONS
  -------------------------
  Nominal Voltage:      ${solution.battery_voltage.toFixed(1)} V
  Capacity:             ${solution.battery_capacity.toFixed(1)} Ah
  Total Energy:         ${formatUnit(solution.battery_energy, "Wh")}
  Max Continuous Power: ${formatUnit(solution.continuous_power, "W")}
  Peak Power (30s):     ${formatUnit(solution.peak_power, "W")}

  MECHANICAL SPECIFICATIONS
  -------------------------
  Total Cell Weight:    ${solution.battery_weight.toFixed(2)} kg (Cells only)
  Cell Dimensions:      ${solution.cell.Cell_Width}x${solution.cell.Cell_Height} mm

  COMPONENTS LIST
  ---------------
  BMS:    ${solution.bms ? `${solution.bms.brand} ${solution.bms.model}` : "Not selected"}
  Fuse:   ${solution.fuse ? `${solution.fuse.brand} ${solution.fuse.model}` : "Not selected"}
  Relay:  ${solution.relay ? `${solution.relay.brand} ${solution.relay.model}` : "Not selected"}

  SAFETY
  ------
  Safety Score: ${solution.safety.safety_score}/100
  Status: ${solution.safety.is_safe ? "PASS" : "WARNING"}
  Warnings: ${solution.safety.warnings.length > 0 ? solution.safety.warnings.join("; ") : "None"}

  --------------------------------------------------
  Disclaimer: This datasheet is generated automatically and is for reference only. 
  Always verify specifications with component manufacturers.
      `;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Datasheet_${solution.series_cells}S${solution.parallel_cells}P.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-6xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl flex items-center gap-2">
            Configuration: {solution.cell.CellModelNo} ({solution.series_cells}S{solution.parallel_cells}P)
            <Badge className={solution.safety.is_safe ? "bg-emerald-600" : "bg-red-600"}>
              Safety Score: {solution.safety.safety_score}
            </Badge>
          </DialogTitle>
        </DialogHeader>

        <div className="bg-orange-50 border-l-4 border-orange-500 p-4 my-4 rounded-r-lg">
          <div className="flex">
            <div className="flex-shrink-0">
              <InfoTooltip content="Important Disclaimer" />
            </div>
            <div className="ml-3">
              <p className="text-sm text-orange-700 font-medium">
                <strong>Disclaimer: This calculation is a theoretical suggestion.</strong>
              </p>
              <p className="text-sm text-orange-700 mt-1">
                Building lithium batteries carries significant risks. The results below are automated estimates.
                <strong> Always consult a professional.</strong>
              </p>
            </div>
          </div>
        </div>

        {dataSource === "default" && solution.safety.warnings.length > 0 && (
          <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-lg mb-4">
            <h4 className="font-bold text-amber-800 flex items-center gap-2 mb-2">
              <AlertTriangle className="w-5 h-5" /> Safety Advisories
            </h4>
            <ul className="list-disc pl-5 text-sm text-amber-900 space-y-1">
              {solution.safety.warnings.map((w, i) => (
                <li key={i}>{w}</li>
              ))}
            </ul>
            {solution.safety.recommendations.length > 0 && (
              <div className="mt-3 pt-3 border-t border-amber-200">
                <span className="text-xs font-bold uppercase text-amber-700">Recommendations:</span>
                <ul className="list-disc pl-5 text-sm text-amber-800 mt-1">
                  {solution.safety.recommendations.map((r, i) => (
                    <li key={i}>{r}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-2">
          <div className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Battery Specs</CardTitle>
              </CardHeader>
              <CardContent className="text-sm space-y-1">
                <p><strong>Configuration:</strong> {solution.series_cells}S {solution.parallel_cells}P</p>
                <p><strong>Nominal Voltage:</strong> {solution.battery_voltage.toFixed(1)} V</p>
                <p><strong>Capacity:</strong> {solution.battery_capacity.toFixed(1)} Ah</p>
                <p><strong>Energy:</strong> {formatUnit(solution.battery_energy, "Wh")}</p>
                <p><strong>Continuous Power:</strong> {formatUnit(solution.continuous_power, "W")}</p>
                <p><strong>Peak Power:</strong> {formatUnit(solution.peak_power, "W")}</p>
                <p><strong>Cells' Weight:</strong> {solution.battery_weight.toFixed(2)} kg</p>
                <p className="font-bold mt-2 border-t pt-1">Components Price: ${solution.total_price.toFixed(2)}</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Cell Data</CardTitle>
              </CardHeader>
              <CardContent className="text-sm space-y-1">
                <p><strong>Brand:</strong> {solution.cell.Brand}</p>
                <p><strong>Model:</strong> {solution.cell.CellModelNo}</p>
                <p><strong>Nominal Voltage:</strong> {solution.cell.NominalVoltage}</p>
                <p><strong>Cont. Discharge:</strong> {solution.cell.MaxContinuousDischargeRate}C</p>
                <p><strong>Capacity:</strong> {solution.cell.Capacity / 1000} Ah</p>
                <p><strong>Price/Cell:</strong> ${solution.cell.Price.toFixed(2)}</p>
                <AffiliateLink link={solution.cell.Connection} />
              </CardContent>
            </Card>
          </div>

          <div className="space-y-4">
            <Card className="bg-slate-50 border-slate-200">
              <CardHeader className="pb-2">
                <CardTitle className="text-base flex items-center gap-2">
                  <DollarSign className="w-4 h-4 text-green-600" /> Commercial Tools
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label className="text-xs">Labor Cost ($)</Label>
                    <Input
                      type="number"
                      className="h-8 text-sm"
                      value={laborCost}
                      onChange={(e) => setLaborCost(Number(e.target.value))}
                    />
                  </div>
                  <div>
                    <Label className="text-xs">Shipping Cost ($)</Label>
                    <Input
                      type="number"
                      className="h-8 text-sm"
                      value={shippingCost}
                      onChange={(e) => setShippingCost(Number(e.target.value))}
                    />
                  </div>
                </div>
                <div>
                  <Label className="text-xs">Profit Margin (%)</Label>
                  <Input
                    type="number"
                    className="h-8 text-sm"
                    value={margin}
                    onChange={(e) => setMargin(Number(e.target.value))}
                  />
                </div>
                <div className="pt-2 border-t border-slate-200">
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm font-semibold text-slate-600">Base Cost:</span>
                    <span className="text-sm">${costPrice.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-lg font-bold text-green-700">Final Price:</span>
                    <span className="text-lg font-bold text-green-700">${finalPrice.toFixed(2)}</span>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base flex items-center gap-2">
                  <Download className="w-4 h-4" /> Downloads
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <div className="flex items-center space-x-2 pb-2">
                  <Checkbox
                    id="bomCosts"
                    checked={includeCostsInBom}
                    onCheckedChange={(c) => setIncludeCostsInBom(c as boolean)}
                  />
                  <Label htmlFor="bomCosts" className="text-xs cursor-pointer">Include costs in BOM</Label>
                </div>
                <Button variant="outline" className="w-full justify-start h-9" onClick={() => requireAuthForDownload(downloadBOM)}>
                  <FileSpreadsheet className="w-4 h-4 mr-2 text-green-600" />
                  Download BOM (Excel/CSV)
                  {!isAuthenticated && <Lock className="w-3 h-3 ml-auto text-muted-foreground" />}
                </Button>
                <Button variant="outline" className="w-full justify-start h-9" onClick={() => requireAuthForDownload(downloadDatasheet_word)}>
                  <FileText className="w-4 h-4 mr-2 text-blue-600" />
                  Download Datasheet (Word)
                  {!isAuthenticated && <Lock className="w-3 h-3 ml-auto text-muted-foreground" />}
                </Button>
                <Button variant="outline" className="w-full justify-start h-9" onClick={() => requireAuthForDownload(downloadDatasheet_pdf)}>
                  <FileText className="w-4 h-4 mr-2 text-red-600" />
                  Download Datasheet (PDF)
                  {!isAuthenticated && <Lock className="w-3 h-3 ml-auto text-muted-foreground" />}
                </Button>
              </CardContent>
            </Card>
          </div>

          {showComponents && (
            <div className="space-y-4">
              {solution.bms && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base flex items-center gap-2"><Zap className="w-4 h-4" /> BMS</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm space-y-1">
                    <p><strong>Brand:</strong> {solution.bms.brand}</p>
                    <p><strong>Model:</strong> {solution.bms.model}</p>
                    <p><strong>Spec:</strong> {solution.bms.a_max}A / {solution.bms.max_cells} Cells</p>
                    <p><strong>Price:</strong> ${solution.bms.master_price?.toFixed(2) || solution.bms.price.toFixed(2)}</p>
                    <AffiliateLink link={solution.bms.link} />
                  </CardContent>
                </Card>
              )}
              {solution.fuse && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base flex items-center gap-2"><CheckCircle className="w-4 h-4" /> Fuse</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm space-y-1">
                    <p><strong>Model:</strong> {solution.fuse.brand} {solution.fuse.model}</p>
                    <p><strong>Rating:</strong> {solution.fuse.a_max}A / {solution.fuse.vdc_max}V</p>
                    <p><strong>Price:</strong> ${solution.fuse.price.toFixed(2)}</p>
                    <AffiliateLink link={solution.fuse.link} />
                  </CardContent>
                </Card>
              )}
              {solution.relay && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base">Relay</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm space-y-1">
                    <p><strong>Model:</strong> {solution.relay.brand} {solution.relay.model}</p>
                    <p><strong>Rating:</strong> {solution.relay.a_max}A / {solution.relay.vdc_max}V</p>
                    <p><strong>Price:</strong> ${solution.relay.price.toFixed(2)}</p>
                    <AffiliateLink link={solution.relay.link} />
                  </CardContent>
                </Card>
              )}
              {solution.cable && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base">Cabling</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm space-y-1">
                    <p><strong>Model:</strong> {solution.cable.brand} {solution.cable.model}</p>
                    <p><strong>Cross Section:</strong> {solution.cable.section} mm²</p>
                    <p><strong>Rating:</strong> {solution.cable.a_max} A / {solution.cable.vdc_max} V</p>
                    <AffiliateLink link={solution.cable.link} />
                  </CardContent>
                </Card>
              )}

              {solution.shunt && (
                <Card>
                  <CardHeader>
                    <CardTitle className="text-base">Shunt</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm space-y-1">
                    <p><strong>Model:</strong> {solution.shunt.brand} {solution.shunt.model}</p>
                    <p><strong>Rating:</strong> {solution.shunt.a_max} A / {solution.shunt.vdc_max} V</p>
                    <AffiliateLink link={solution.shunt.link} />
                  </CardContent>
                </Card>
              )}
            </div>
          )}
        </div>

        {showComponents && (
          <div className="mb-6 mt-4">
            <Button
              variant="outline"
              className="w-full flex items-center justify-between border-slate-300 text-slate-700 hover:bg-slate-50"
              onClick={() => setShowDiagram(!showDiagram)}
            >
              <span className="flex items-center gap-2">
                <CircuitBoard className="w-4 h-4 text-amber-600" />
                {showDiagram ? "Hide Wiring Diagram" : "Show Wiring Diagram"}
              </span>
              {showDiagram ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
            </Button>

            {showDiagram && (
              <div className="mt-4 animate-in fade-in zoom-in-95 duration-300">
                <WiringDiagram config={solution} />
              </div>
            )}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};
